# Generated by Django 3.2.5 on 2021-07-08 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_time',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings_winning', to=settings.AUTH_USER_MODEL),
        ),
    ]
