# Generated by Django 3.2.5 on 2021-07-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210708_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='bidder',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='current_winner',
        ),
    ]
