# Generated by Django 3.2.5 on 2021-07-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210709_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='listing',
        ),
    ]
