# Generated by Django 3.2.5 on 2021-07-09 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210709_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_listings',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='watcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
