# Generated by Django 3.2.5 on 2021-07-09 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210709_0411'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('watcher', 'listing')},
        ),
    ]
